### ISSUE TITLE
Add ability to add comments

### ISSUE THREAD

**Issue by bamohan** [katharinap/my_recipes#10]
<a href="https://github.com/bamohan"><img src="https://avatars.githubusercontent.com/u/2954424?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bamohan](https://github.com/bamohan)**
_Wednesday Apr 06, 2016 at 04:22 GMT_
_Originally opened as https://github.com/katharinap/cookie/issues/10_

---

**Comment by katharinap** [comment]
What's the difference between notes and comments for #9?

**Comment by bamohan** [comment]
Notes and Comments would be the same thing :).

**Comment by katharinap** [comment]
I'll call it notes then.  This is meant for notes of the recipe's owner, right?  E.g. to mention that something needs to be soaked overnight or that you could swap some ingredient with something else?  We could use comments later on for comments of other users.
