### ISSUE TITLE
add ability to add cook time, prep time etc

### ISSUE THREAD

**Issue by bamohan** [katharinap/my_recipes#13]
<a href="https://github.com/bamohan"><img src="https://avatars.githubusercontent.com/u/2954424?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bamohan](https://github.com/bamohan)**
_Wednesday Apr 06, 2016 at 04:22 GMT_
_Originally opened as https://github.com/katharinap/cookie/issues/13_

---
- add to recipe model
- add to all views
- add indexes for these 2 fields

**Comment by katharinap** [comment]
resolved with #66
